server:
  port: 8082

spring:
  application:
    name: database-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/productData?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      feed: feed-topic
    consumer:
      group-id: user-service-group
      auto-offset-reset: latest