server:
  port: 8081

spring:
  application:
    name: database-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/?user=root
    username: root
    password: {DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop