server:
  port: 8080

spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      feed: feed-topic
    consumer:
      group-id: user-service-group
      auto-offset-reset: latest

